version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:latest
    networks:
      - app-network
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: revanthgundala/builder_connect:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - MONGOURI=${MONGOURI}
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
      - HUGGING_FACE_API_URL=${HUGGING_FACE_API_URL}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_TOKEN_URL=${GOOGLE_OAUTH_TOKEN_URL}
      - GOOGLE_OAUTH_AUTH_URL=${GOOGLE_OAUTH_AUTH_URL}
      - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
      - DISCORD_OAUTH_TOKEN_URL=${DISCORD_OAUTH_TOKEN_URL}
      - DISCORD_OAUTH_AUTH_URL=${DISCORD_OAUTH_AUTH_URL}
      - DISCORD_OAUTH_CLIENT_ID=${DISCORD_OAUTH_CLIENT_ID}
      - DISCORD_OAUTH_CLIENT_SECRET=${DISCORD_OAUTH_CLIENT_SECRET}
      - DISCORD_OAUTH_REDIRECT_URL=${DISCORD_OAUTH_REDIRECT_URL}
      - BUILDWORK_EMAIL=${BUILDWORK_EMAIL}
      - BUILDWORK_EMAIL_PASSWORD=${BUILDWORK_EMAIL_PASSWORD}
      - PRODUCTION_URL=${PRODUCTION_URL}
      - LOCALHOST=${LOCALHOST}
      - LOCALHOST_API=${LOCALHOST_API}
      - PRODUCTION_API=${PRODUCTION_API}
      - IN_PRODUCTION=${IN_PRODUCTION}
    depends_on:
      - mongodb
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - api
      - redis
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  app-network:
    driver: bridge
volumes:
  mongodb: {}
