version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGOURI=${MONGOURI}
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
      - HUGGING_FACE_API_URL=${HUGGING_FACE_API_URL}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_TOKEN_URL=${GOOGLE_OAUTH_TOKEN_URL}
      - GOOGLE_OAUTH_AUTH_URL=${GOOGLE_OAUTH_AUTH_URL}
      - GOOGLE_OAUTH_REDIRECT_URL=${GOOGLE_OAUTH_REDIRECT_URL}
      - DISCORD_OAUTH_TOKEN_URL=${DISCORD_OAUTH_TOKEN_URL}
      - DISCORD_OAUTH_AUTH_URL=${DISCORD_OAUTH_AUTH_URL}
      - DISCORD_OAUTH_CLIENT_ID=${DISCORD_OAUTH_CLIENT_ID}
      - DISCORD_OAUTH_CLIENT_SECRET=${DISCORD_OAUTH_CLIENT_SECRET}
      - DISCORD_OAUTH_REDIRECT_URL=${DISCORD_OAUTH_REDIRECT_URL}
      - BUILDER_CONNECT_EMAIL=${BUILDER_CONNECT_EMAIL}
      - BUILDER_CONNECT_EMAIL_PASSWORD=${BUILDER_CONNECT_EMAIL_PASSWORD}
      - PRODUCTION_URL=${PRODUCTION_URL}
      - IN_PRODUCTION=${IN_PRODUCTION}
    depends_on:
      - mongodb
      - redis
volumes:
  mongodb: {}
