name: Builder Connect

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    runs-on: ubuntu-latest
    working-directory: ./builder_connect

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
    frontend:
      runs-on: ubuntu-latest
      working-directory: ./builder_connect_ui

      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        - name: Run tests
          run: npm run test
