CREATE TABLE users (
    id SERIAL NOT NULL PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    github TEXT,
    website TEXT,
    age INT,
    age_weight INT,
    location TEXT,
    location_weight INT,
    employer TEXT,
    employer_weight INT,
    reason TEXT,
    project_interests TEXT,
    project_interests_weight INT,
    personality_interests TEXT,
    personality_interests_weight INT,
    skills TEXT,
    skills_weight INT,
    right_swipes INTEGER[],
    left_swipes INTEGER[],
    incoming_right_swipes INTEGER[],
    incoming_left_swipes INTEGER[],
    matches INTEGER[],
);