CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  github TEXT,
  website TEXT,
  age INT,
  age_weight INT,
  location TEXT,
  location_weight INT,
  employer TEXT,
    employer_weight INT,
    reason TEXT,
    interests TEXT,
    interests_weight INT,
    skills TEXT,
    skills_weight INT,
);